### ISSUE TITLE
Wrong command use response is too unspecific

### ISSUE THREAD

**Issue by rschmidtner** [larryhastings/appeal#18]
When I a use command wrongly Appeal bascially tells me "you did use the command wrong". It would be nice to be more specific about what exactly I did wrong.  

E.g. with the following script

```
#script.py
import appeal

app = appeal.Appeal()

@app.command()
def f(a:int):
    pass


if __name__ == "__main__":
    app.main()
```

when I  run `python script.py f "not an int"` Appeal returns
```
usage: script.py command

Commands:

    f
    help            Print usage documentation on a specific command.
```
It would be nice to get this + something like "parameter `a` needs to be of type `int` but got passed as type `str`"

**Comment by larryhastings** [comment]
Thanks for the report!  Appeal was designed to print something very like what you asked for.  All the code was in and working, except it was commented out at the very end.  I've re-enabled it and it seems to be fine.  Scratching my head at what I was thinking here.

I also hacked it up a little so it produces context-specific help, like it should.  The result of your test script is now

```
% python3 script.py f "not an int"
Error: invalid value 'not an int' for a, must be int

usage: script.py f a
```

I'll do some other maintenance on Appeal and release an update with this fix soon.
