### ISSUE TITLE
appeal steals all stdout (bug?)

### ISSUE THREAD

**Issue by sotte** [larryhastings/appeal#19]
First of all, I really like appeal!

I wanted to use [cog](https://nedbatchelder.com/code/cog) to update the help text in the README of a CLI that I build with appeal. For this I just wanted to capture stdout. However, appeal seems to capture all stdout and does not give it back.

Here is a little debug script.
```
import io
from contextlib import redirect_stdout

from my_package.__main__ import main  # this is the appeal cli

# main()  # if this is enabled, appeal steals all output. Should this be the case?

print("before")
temp_out = io.StringIO()
with redirect_stdout(temp_out):
    print("hello")
    # main()  # this is really what I want to capture to get the help text
print("after")

print(temp_out.getvalue())
```
Output:
```
before
after
hello
```
If I uncomment the first `main()`, I only get the help of main, nothing else.
If I uncomment the second `main()`, I only get
```
before
```

I'm not sure if this is the intended behavior or if there is a better way to do what I wanted  to do or if this  is a bug.

____

Note: with click I normally use the `CLIRunner` to conveniently captures stdout and then update the readme:

```python
import cog
from click.testing import CliRunner
runner = CliRunner()
result = runner.invoke(my_cli.cli, ["--help"])
cog.out(resut.output)
```

**Comment by larryhastings** [comment]
Hi!  Sorry for the slow reply, I've been busy.

There's literally no code in Appeal that touches stdout/stderr (apart from printing to it with `print`).  Literally, the only reference to stdout and stderr in all of Appeal [is in a comment.](https://github.com/larryhastings/appeal/blob/master/appeal/__init__.py#L4723)  So I don't understand how Appeal could be stealing stdout in your program.

If you could give me a standalone script that demonstrates the error, I'll look in to it.  For now I'm guessing this is a side-effect of some other library you're using.

p.s. Click's mission creep is one of the reasons I don't like Click, and why I wrote Appeal.  Appeal will never hijack stdio.
