### ISSUE TITLE
Bug: README mentions missing document for how to write documentation

### ISSUE THREAD

**Issue by sotte** [larryhastings/appeal#20]
https://github.com/larryhastings/appeal#writing-help mentions the document `appeal/notes/writing.documentation.txt` which does not exist.

**Comment by LennyN95** [comment]
I came here to open the same issue. Is this feature not yet (fully) implemented or is the file just missing?

**Comment by larryhastings** [comment]
Long ago, before Appeal was released to the public, that document existed, and I removed it.  Appeal itself is experimental, and aspects of the "how to write documentation" approach are... _extra_ experimental.

I'll past a copy of it in here to satisfy your curiosity.  But honestly I think Appeal's approach to documentation needs a bit of a re-think.  My theory is that it's too complicated, and could be simplified somehow, and I keep hoping that inspiration will strike and I'll figure out how to make it much better.

[writing.documentation.txt](https://github.com/user-attachments/files/16912809/writing.documentation.txt)
